### ISSUE TITLE
Why do you not show the source code?

### ISSUE THREAD

**Issue by Zseni051** [Gucci637/Fentanyl#31]
How do I know this doesn't steal my token.

**Comment by Nostorian** [comment]
see issue #21

**Comment by Gucci637** [comment]
> How do I know this doesn't steal my token.

**1. Skids**
Skids are annoying and will steal the code, say it's their own, and probably try to profit off it.

**2. Discord**
If I show the source, Discord will patch it 10x faster.

**Comment by Gucci637** [comment]
[COPY + PASTED MESSAGE] You can visit the new discord server here!
https://discord.gg/e4k4SSYBMz
